<!doctype html>
<head>
  <?php echo $this->headMeta(); ?>
  <?php
  $currentController = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
  $currentAction = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
  ?>
  <?php echo $this->headLink()
				->prependStylesheet($this->baseUrl().'/resources/css/reset.css')
				->appendStylesheet($this->baseUrl().'/resources/css/style.css');
      
      $defaultNamespace = new Zend_Session_Namespace('Default');
?>
  <title>ihealth</title>
</head>
<body>
  <div class="blue-fade"></div>
		<img class="img-bg" src="/resources/img/artzt.png" />
	
		<div class="top-gray"></div>		
		<div class="outter-content">
    <img src="/resources/img/imed_logo.png" id="imed-logo"/>
		<div class="content">

      <h1><?php echo $this->escape($this->title); ?></h1>
			<?php         
        if(!empty($this->flashMessages)) {
            echo '<div class="flash-messages">';

            foreach($this->flashMessages as $key => $value) {
                echo $this->translate($value)."<br />";
            }
            echo '</div>';
        }
        
        // content from each view, the rest of this page is global to all views
        echo $this->layout()->content;
        ?>
    <div style="clear: left"> </div>
		</div>
    </div>
		<div class="navigation">
			<ul>
				<li class="home">					
					<a href="/index/index">
						<p class="option">Startseite</p>
						<p class="description">Überblick über Ihre Funktionen.</p>
					</a>
				</li>
				<?php 
          if(Zend_Auth::getInstance()->hasIdentity()) { ?>
        <?php if($defaultNamespace->user->hasRight(CRUD_PATIENTS)) { ?>
        <li class="patient">					
					<a href="/patient/list">
						<p class="option">Patienten</p>
						<p class="description">Verwalten Sie Ihre Patienten.</p>
					</a> 

				</li>
        <?php } if($defaultNamespace->user->hasRight(CRUD_RFID)) { ?>
				<li class="rfid">
					<a href="/rfid/list">
						<p class="option">RFID-Tags</p>
						<p class="description">Verwalten Sie Ihre RFID-Tags.</p>
					</a>
				</li>
        <?php } if($defaultNamespace->user->hasRight(CRUD_PERSONNEL)) { ?>
        <li class="personnel">
					<a href="/personnel/list">
						<p class="option">Personal</p>
						<p class="description">Verwalten Sie die Benutzer des Systems.</p>
					</a>
				</li>
        <?php } ?>
                <li class="register">
					<a href="/personnel/update-profile">
						<p class="option">Eigenes Profil bearbeiten</p>
						<p class="description"></p>
					</a>
				</li>
        <li class="lock">
					<a href="/auth/logout">
						<p class="option">Abmelden</p>
						<p class="description"></p>
					</a>
				</li>
        <?php } else { ?>
				<li class="lock">
					<a href="/auth/login">
						<p class="option">Anmelden</p>
						<p class="description"></p>
					</a>
				</li>
        <li class="register">
					<a href="/personnel/register">
						<p class="option">Registrieren</p>
						<p class="description"></p>
					</a>
				</li>
        <?php } ?>          
          
			</ul>
			<div class="nav-info-wrapper">
				<div class="nav-info-bg"></div>
				<span class="nav-info">aktion wählen</span>
			</div>
		</div>
		<script src="/resources/js/jquery.min.js"></script>
    <script src="/resources/js/jquery.easing.1.3.js"></script>
		<script src="/resources/js/page.js"></script>
    
   
</body>
</html>