<!doctype html>
<head>
  <?php echo $this->headMeta(); ?>
  <?php
  $currentController = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
  $currentAction = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
  ?>
  <?php echo $this->headLink()
				->prependStylesheet($this->baseUrl().'/resources/css/styles.css');
			//	->appendStylesheet($this->baseUrl().'/css/navi_de.css')
      
      $defaultNamespace = new Zend_Session_Namespace('Default');
?>

</head>
<body>
  <div id="page">
    <div id="header">
        <div id="top-menu">
          <ul>
          <li class="button<?php if($currentController == "index") { echo " active"; } ?>">
            <a href="/index/index"><span class="left">&nbsp;</span><span class="home">&nbsp;</span><span class="right">&nbsp;</span></a>
          </li>
          <?php 
          if(Zend_Auth::getInstance()->hasIdentity()) { ?>
          <li class="button<?php if($currentController == "personnel") { echo " active"; } ?>">
            <a href="/personnel/list"><span class="left">&nbsp;</span>Personal<span class="right">&nbsp;</span></a>
          </li>
             <li class="button<?php if($currentController == "rfid") { echo " active"; } ?>">
            <a href="/rfid/list"><span class="left">&nbsp;</span>RFID-Tags<span class="right">&nbsp;</span></a>
          </li>
          <li class="button<?php if($currentController == "patient") { echo " active"; } ?>">
            <a href="/patient/list"><span class="left">&nbsp;</span>Patienten<span class="right"nbsp;</span></a>
          </li>
           <li class="button<?php if($currentController == "measurement") { echo " active"; } ?>">
            <a href="/measurement/list"><span class="left">&nbsp;</span>Messungen<span class="right">&nbsp;</span></a>
          </li>
          <?php
        } ?>
        </ul>
        </div>
    </div>
    <div id="content">
      <div id="sub-menu">
        <?php if(Zend_Auth::getInstance()->hasIdentity()) { ?>
          <?php 
                echo $this->translate("Welcome") ." " .  $defaultNamespace->user->getUsername() . "!";
                ?>
            <a href="/personnel/edit/id/<?php echo $defaultNamespace->user->getId(); ?>"><span class="left">&nbsp;</span><?php echo $this->translate("Edit profile"); ?><span class="right"nbsp;</span></a>
                <a href="/auth/logout"><?php echo $this->translate("Logout"); ?></a>
                <?php
           } else { ?>
              <?php echo $this->translate("You are not logged in."); ?>
              <a href="/personnel/register"><?php echo $this->translate("Register now"); ?></a> 
              or <a href="/auth/login"><?php echo $this->translate("Login"); ?></a>
        <?php } ?>
       </div>
      <h1><?php echo $this->escape($this->title); ?></h1>
      <div id="main">
        <?php 
        if(!empty($this->flashMessages)) {
            echo '<div class="flash-messages">';

            foreach($this->flashMessages as $key => $value) {
                echo $this->translate($value)."<br />";
            }
            echo '</div>';
        }
        
        // content from each view, the rest of this page is global to all views
        echo $this->layout()->content;
        ?>
      </div>
      
     
      </div>
    </div>
  </div>
  <div>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="/resources/js/libs/jquery-1.6.2.min.js"><\/script>')</script>
</body>
</html>