<?php
$this->title = "Liste Krankenhausaufenthalte";
$this->headTitle($this->title);
?>
<div class="data-column">
  <div class="data-content">
    <div class="filler-block">
      <?php echo $this->patient->getPatientData(); ?>
    </div>

    <table cellpadding="0" cellspacing="0" class="default"> 
      <tr>
        <th>ICD</th>
        <th style="width: 200px;">OPS</th>
        <th style="width: 150px;">Krankenhaus</th>
        <th style="width: 75px;">Check in /<br />
          Check out</th>
      </tr>
      <?php
      $i = 0;
      foreach($this->listHospitalStays as $hospitalStay):
        ?>
        <tr <?php $i++;
      echo ($i % 2 != 0) ? "class=\"even\"" : ""; ?>>
          <td><?php echo $hospitalStay->getIcd(); ?></td>
          <td><?php echo $hospitalStay->getOps(); ?></td>
          <td><?php echo ($hospitalStay->getHospital()) ? $hospitalStay->getHospital()->getName() : "-"; ?></td>
          <td><?php echo $hospitalStay->getCheckIn()->format("Y-m-d"); ?> / <?php echo ($hospitalStay->getHospital()) ? $hospitalStay->getCheckOut()->format("Y-m-d") : "im KH"; ?></td>
        </tr>
<?php endforeach; ?>
    </table>

  </div>
</div>
<div id="user-pic">
  <a href="/patient/overview/id/<?php echo $this->patient->getId(); ?>"><img src="/resources/img/user_123.png" /></a>
  <a href="/patient/overview/id/<?php echo $this->patient->getId(); ?>">zurück zum Profil</a>
</div>
