<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_PersonnelProxy extends \Application_Model_Personnel implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getAcademicTitle()
    {
        $this->__load();
        return parent::getAcademicTitle();
    }

    public function setAcademicTitle($academicTitle)
    {
        $this->__load();
        return parent::setAcademicTitle($academicTitle);
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setPosition($position)
    {
        $this->__load();
        return parent::setPosition($position);
    }

    public function getLayedIn()
    {
        $this->__load();
        return parent::getLayedIn();
    }

    public function setLayedIn($layedIn)
    {
        $this->__load();
        return parent::setLayedIn($layedIn);
    }

    public function getLayedOut()
    {
        $this->__load();
        return parent::getLayedOut();
    }

    public function setLayedOut($layedOut)
    {
        $this->__load();
        return parent::setLayedOut($layedOut);
    }

    public function getDegreeDate()
    {
        $this->__load();
        return parent::getDegreeDate();
    }

    public function setDegreeDate($degreeDate)
    {
        $this->__load();
        return parent::setDegreeDate($degreeDate);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getVerificationHash()
    {
        $this->__load();
        return parent::getVerificationHash();
    }

    public function setVerificationHash($verificationHash)
    {
        $this->__load();
        return parent::setVerificationHash($verificationHash);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function hasRight($right)
    {
        $this->__load();
        return parent::hasRight($right);
    }

    public function setRight($right, $hasRight)
    {
        $this->__load();
        return parent::setRight($right, $hasRight);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'email', 'username', 'password', 'academicTitle', 'firstname', 'lastname', 'state', 'position', 'layedIn', 'layedOut', 'degreeDate', 'verificationHash', 'rights');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}