<?php
    $this->title = "Patienten Listenansicht";
    $this->headTitle($this->title);
?>
<table cellpadding="0" cellspacing="0" class="default"> 
  <tr>
    <th>Name</th>
    <th style="width: 150px;">Feld 2</th>
    <th style="width: 200px;">Aktionen</th>
  </tr>
  <?php 
  $i = 0;
  foreach($this->listPatients as $patient): 
    ?>
  <tr <?php echo ($i++ %2 == 0) ? "class=\"even\"" : ""; ?>>
    <td><?php echo $patient->getName(); ?></td>
    <td>kommt noch</td>
    <td>[ 
        ]</td>
  </tr>
  <?php endforeach; ?>
</table>
  <a href="/patient/create">Neuen Patient anlegen</a>