<?php
$this->title = "Liste Messungen";
$this->headTitle($this->title);
?>
<div class="data-column">
  <div class="data-content">
    <div class="filler-block">
      <?php echo $this->patient->getPatientData(); ?>
    </div>

    <table cellpadding="0" cellspacing="0" class="default"> 
      <tr>
        <th>Wert</th>
        <th style="width: 200px;">Memo</th>
        <th style="width: 150px;">Personal</th>
        <th style="width: 75px;">Datum</th>
      </tr>
      <?php
      $i = 0;
      foreach($this->listMeasurements as $measurement):
        ?>
        <tr <?php $i++;
      echo ($i % 2 != 0) ? "class=\"even\"" : ""; ?>>
          <td><?php echo $measurement->getValue(); ?> <?php echo $measurement->getType()->getUnit(); ?></td>
          <td><?php echo $measurement->getMemo(); ?></td>
          <td><?php echo $measurement->getPersonnel()->getName(); ?></td>
          <td><?php echo $measurement->getDate()->format("Y-m-d"); ?></td>
        </tr>
<?php endforeach; ?>
    </table>

  </div>
</div>
<div id="user-pic">
  <a href="/patient/overview/id/<?php echo $this->patient->getId(); ?>"><img src="/resources/img/user_123.png" /></a>
  <a href="/patient/overview/id/<?php echo $this->patient->getId(); ?>">zurück zum Profil</a>
</div>
