<?php
$this->title = "Personal Listenansicht";
$this->headTitle($this->title);
?>
<div class="data-column">
  <div class="data-content">
    <div class="filler-block">
    </div>
    <table cellpadding="0" cellspacing="0" class="default"> 
      <tr>
        <th>Name</th>
        <th style="width: 150px;">Position</th>
        <th style="width: 200px;">Aktionen</th>
      </tr>
      <?php
      $i = 0;
      foreach($this->listPersonnel as $personnel):
        ?>
        <tr <?php echo ($i++ % 2 == 0) ? "class=\"even\"" : ""; ?>>
          <td><?php echo $personnel->getUsername(); ?> <?php echo $personnel->getFirstname() . " " . $personnel->getLastname(); ?></td>
          <td><?php if($personnel->getPosition())
        echo $personnel->getPosition()->getTitle(); ?></td>
          <td>[ 
            <a href="<?php echo "/personnel/edit/id/" . $personnel->getId(); ?>">bearbeiten</a>
            ]</td>
        </tr>
<?php endforeach; ?>
    </table>
  </div>
</div>
<div id="icon">
  <img src="/resources/icons/personnel.png" />
</div>