<?php
$this->title = "RFID-Tags Listenansicht";
$this->headTitle($this->title);
?>
<div class="data-column">
  <div class="data-content">
    <div class="filler-block">
    </div>
    <table cellpadding="0" cellspacing="0" class="default"> 
      <tr>
        <th>RFID-Tag</th>
        <th style="width: 150px;">Aktueller Patient</th>
        <th style="width: 200px;">Aktionen</th>
      </tr>
      <?php
      $i = 0;
      foreach($this->listRfidTags as $rfidTag):
        ?>
        <tr <?php echo ($i++ % 2 == 0) ? "class=\"even\"" : ""; ?>>
          <td><?php echo $rfidTag->getTag(); ?></td>
          <td><?php if($rfidTag->getPatient()){
        echo $rfidTag->getPatient()->getName();
      }else{
        echo "<i style=\"color: #999999\">nicht zugewiesen</i>";
      } ?></td>
          <td>[ <?php if($rfidTag->getPatient()){
        echo "<a href=\"/rfid/clear/id/" . $rfidTag->getId() . "\">freigeben</a>";
      } ?>
  <?php if(!$rfidTag->getPatient()){
    echo "<a href=\"/rfid/delete/id/" . $rfidTag->getId() . "\">entfernen</a>";
  } ?>
            ]</td>
        </tr>
<?php endforeach; ?>
    </table>
    <a href="/rfid/create">Neuen Tag anlegen</a>
  </div>
</div>
<div id="icon">
  <img src="/resources/icons/rfid.png" />
</div>